CREATE USER <user> WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD '<password>';
CREATE DATABASE <database> WITH OWNER = <user> ENCODING = 'UTF8' CONNECTION LIMIT = -1;
