== Testing
=== General
AppNG also offers support for unit- and integration testing your appNG applications. Therefore, it uses the testing capabilities of the Spring framework. See the {spring}/spring-framework-reference/htmlsingle/#testing[Reference Documentation^] for details on testing with Spring.

To enable test support, just add the following dependency to your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>org.appng</groupId>
    <artifactId>appng-testsupport</artifactId>
    <version>${appNG.version}</version>
</dependency>
----

Next, use {appng}/org/appng/testsupport/TestBase.html[org.appng.testsupport.TestBase^] as a base class for your unit tests. You can test with or without JPA support enabled.

Without JPA support:
[source,java]
----
@org.springframework.test.context.ContextConfiguration(initializers = MyTest.class)
public class EmployeesTest extends TestBase {

    public EmployeesTest() {
        super("myapp", "application-home");
    }
    
}
----

With JPA support:
[source,java]
----
@org.springframework.test.context.ContextConfiguration(
    locations = { TestBase.TESTCONTEXT_JPA }, initializers = MyTest.class)
public class EmployeesTest extends TestBase {

    public EmployeesTest() {
        super("myapp", "application-home");
        setEntityPackage("com.myapp.domain");
        setRepositoryBase("com.myapp.repository");
    }
 
}
----

=== Testing a datasource:
[source,java]
----
@org.junit.Test
public void testShowEmployees() throws ProcessingException, IOException {
	addParameter("selectedId", "1"); // <!--1-->
	initParameters(); // <!--2-->
	DataSourceCall dataSourceCall = getDataSource("employees");// <!--3-->
	CallableDataSource callableDataSource = dataSourceCall.getCallableDataSource(); // <!--4-->
	callableDataSource.perform("aPage"); // <!--5-->
	validate(callableDataSource.getDatasource());// <!--6-->
}
----
<1> adds a parameter
<2> initialize the parameters, must be called after parameters have been added
<3> retrieve a `DataSourceCall` representing the datasource by its id
<4> get a `CallableDataSource`
<5> perform the `CallableDataSource`
<6> validate the response

In step 6, a {appng}/org/appng/testsupport/validation/WritingXmlValidator.html[org.appng.testsupport.validation.WritingXmlValidator^] is used to compare the contents of a *control file* with the XML that results from marshalling the given object (in this case a `org.appng.xml.platform.Datasource`). The control file must be located at `src/test/resources/xml`. It's name is derived from the name of the test class and the name of the test method. So in this example, it would be `EmployeesTest-testShowEmployees.xml`.

NOTE: For initially creating and later updating your control files, just set `WritingXmlValidator.writeXml = true` and the control files will be written to `src/test/resources/xml`. 

=== Testing an action:
[source,java]
----
@org.junit.Test
public void testCreateEmployee() throws ProcessingException, IOException {
	ActionCall action = getAction("employeeEvent", "create");// <!--1-->
	action.withParam(FORM_ACTION, "create");// <!--2-->
	Employee formBean = new Employee("John", "Doe");// <!--3-->
	CallableAction callableAction = action.getCallableAction(formBean);// <!--4-->
	FieldProcessor fieldProcessor = callableAction.perform();// <!--5-->
	validate(fieldProcessor.getMessages(), "-messages");// <!--6-->
	validate(callableAction.getAction(), "-action");// <!--7-->
}
----
<1> retrieve an `ActionCall` representing the action by its event-id and id
<2> add required parameters to the action
<3> create a form bean
<4> retrieve a `CallableAction`
<5> perform the `CallableAction` receive a `FieldProcessor`
<6> use a `validate(...)`-method that takes a suffix as a parameter, validating the messages of the `fieldProcessor`
<7> use the same validate method to validte the contents of the action

NOTE: Although you pass the `formBean` as a whole to `ActionCall.getCallableAction(formBean)`, this `formBean` is being copied internally. This copy, which is passed to the `ActionProvider<T>`, will contain only those properties that are mapped and writable in the datasource used by the action.

=== Adding custom bean definitions for testing
You can add custom bean definitons for your tests. For example, if you want to run a SQL script to initialize your test database, you could provide a file `beans-test-xml` located at `src/test/resources`.

.beans-test.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:jdbc="http://www.springframework.org/schema/jdbc"
	xsi:schemaLocation="http://www.springframework.org/schema/jdbc
		http://www.springframework.org/schema/jdbc/spring-jdbc.xsd
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans.xsd">
	
	<jdbc:initialize-database enabled="true" data-source="datasource"><!--1-->
		<jdbc:script location="classpath:/sql/init-db.sql" /><!--2-->
	</jdbc:initialize-database>
</beans>
----
<1> use `<jdbc:initialize-database>` and make a reference to the built in <<app-datasource, datasource>>
<2> set the classpath location for the DDL script

In your testcase, you just need to add `beans-test.xml` to the `@ContextConfiguration`-annotation 

[source,java]
----
@ContextConfiguration(locations = { TestBase.TESTCONTEXT_JPA, "classpath:/beans-test.xml" }
----