create table job_execution_record (
	id integer generated by default as identity (start with 1),
	application varchar(255),
	site varchar(255),
	job_name varchar(255),
	start timestamp,
	end timestamp,
	duration INT,
	run_once BIT,
	result varchar(255),
	stacktraces VARCHAR(1000000),
	custom_data VARCHAR(1000000),
	triggername varchar(255),	
	primary key (id)
);
