create table job_execution_record (
	id int4 generated by default as identity,
	application varchar(255),
	site varchar(255),
	job_name varchar(255),
	start_time timestamp,
	end_time timestamp,
	duration INT,
	run_once boolean,
	result varchar(255),
	stacktraces text,
	custom_data text,
	triggername varchar(255),	
	primary key (id)
);
